name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup yarn
        uses: actions/setup-node@v4
        with:
          node-version: "14"
      - run: npm i -g yarn

      - name: Add dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Push
        uses: actions-x/commit@v6
        with:
          email: 41898282+github-actions[bot]@users.noreply.github.com
          name: github-actions[bot]
          files: dist src/themes
          message: automated regeneration
